name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Runs every time you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew :composeApp:jsBrowserDistribution

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: composeApp/build/dist/js/productionExecutable # The folder we found earlier
          branch: gh-pages # The branch where the website lives